import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from "@/app/context/auth-provider";
import Navbar from "@/app/components/navbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Firebase 9',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <Navbar />
        <main className="flex justify-center items-start p-6 min-h-screen">
          {children}
        </main>
      </AuthProvider>
      </body>
      </html>
  )
}
